// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, httpProxy, proxy, proxyOptions;

  express = require('express');

  httpProxy = require('http-proxy');

  app = express();

  proxy = new httpProxy.RoutingProxy();

  proxyOptions = {
    host: '192.168.1.12',
    port: '6544'
  };

  app.get('/Video/*', function(req, res) {
    console.log("We are doing a request");
    return proxy.proxyRequest(req, res, proxyOptions);
  });

  app.listen(3000);

}).call(this);
